# Mock database seed list containing 50 prominent AI startups/companies
# Used for Phase IV Deterministic Entity Resolution

CANONICAL_STARTUPS = [
    "OpenAI",
    "Anthropic",
    "Google DeepMind",
    "Meta",
    "xAI",
    "Mistral AI",
    "Cohere",
    "Hugging Face",
    "Midjourney",
    "Stability AI",
    "Jasper",
    "Copy.ai",
    "Character.ai",
    "Perplexity",
    "Runway",
    "ElevenLabs",
    "Scale AI",
    "Adept AI",
    "Inflection AI",
    "Harvey",
    "Glean",
    "Writer",
    "Synthesia",
    "Pika Labs",
    "AssemblyAI",
    "Baseten",
    "Replicate",
    "Together AI",
    "Anyscale",
    "LangChain",
    "LlamaIndex",
    "Weights & Biases",
    "Pinecone",
    "Milvus",
    "Qdrant",
    "Weaviate",
    "Chroma",
    "Deci AI",
    "Imbue",
    "Cognition",
    "Phind",
    "Cursor",
    "Magic",
    "Vercel",
    "Supabase",
    "Neon",
    "Modal Labs",
    "CoreWeave",
    "Lambda Labs",
    "Groq"
]
